services:
  postgres:
    image: postgres:14.20-trixie
    container_name: postgres-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 9mREsvXDs9Gk89Ef
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: